disease(malaria).
disease(neonatal_sepsis).
disease(hiv_aids).
disease(tuberculosis).
disease(pneumonia).
disease(cholera).
disease(chronic_kidney_disease).
disease(typhoid_fever).
disease(lassa_fever).
disease(sickle_cell_disease).
disease(hypertension).
disease(diabetes_mellitus_type_2).
disease(hepatitis_b).
disease(bacterial_meningitis).
disease(peptic_ulcer_disease).
disease(asthma).
disease(measles).
disease(urinary_tract_infection).
disease(pyelonephritis).
disease(yellow_fever).
disease(glaucoma).
disease(acute_angle_closure_glaucoma).
disease(lymphatic_filariasis).
disease(onchocerciasis).
disease(river_blindness).
disease(acute_otitis_media).
disease(otitis_media).
disease(meningococcal_disease).
disease(meningococcal_meningitis).
disease(gastroenteritis).
disease(hepatitis_c).