symptom(fever).
symptom(chills).
symptom(headache).
symptom(body_pain).
symptom(nausea).
symptom(weakness).
symptom(sweats).
symptom(vomiting).
symptom(sweating).
symptom(poor_feeding).
symptom(lethargy).
symptom(fast_breathing).
symptom(grunting).
symptom(irritability).
symptom(jaundice).
symptom(seizures).
symptom(poor_cry).
symptom(hypothermia).
symptom(recurrent_fever).
symptom(weight_loss).
symptom(chronic_diarrhea).
symptom(night_sweats).
symptom(persistent_cough).
symptom(oral_thrush).
symptom(swollen_lymph_nodes).
symptom(recurrent_infections).
symptom(high_risk_exposure).
symptom(young_adult).
symptom(cough_two_plus_weeks).
symptom(chest_pain).
symptom(hemoptysis).
symptom(fatigue).
symptom(hiv_exposure).
symptom(close_tb_contact).
symptom(cough).
symptom(breathlessness).
symptom(chest_pain_worse_with_breathing).
symptom(sputum_production).
symptom(reduced_oxygen_saturation).
symptom(confusion).
symptom(sudden_watery_diarrhea).
symptom(severe_dehydration).
symptom(muscle_cramps).
symptom(sunken_eyes).
symptom(unsafe_water_exposure).
symptom(outbreak_exposure).
symptom(edema).
symptom(foamy_urine).
symptom(nocturia).
symptom(reduced_appetite).
symptom(hypertension).
symptom(itching).
symptom(metallic_taste).
symptom(known_diabetes).
symptom(known_hypertension).
symptom(muscle_cramps).
symptom(prolonged_fever).
symptom(abdominal_pain).
symptom(constipation).
symptom(diarrhea).
symptom(unsafe_food_water).
symptom(rose_spots).
symptom(intestinal_perforation).
symptom(gastrointestinal_bleeding).
symptom(sore_throat).
symptom(chest_pain).
symptom(abdominal_pain).
symptom(dry_season).
symptom(hemorrhage).
symptom(bleeding_gums).
symptom(facial_swelling).
symptom(rodent_exposure).
symptom(respiratory_distress).
symptom(pericarditis).
symptom(hearing_loss).
symptom(recurrent_painful_crises).
symptom(anemia).
symptom(delayed_growth).
symptom(hand_foot_swelling).
symptom(family_history).
symptom(dactylitis).
symptom(throbbing_morning_headache).
symptom(nosebleeds).
symptom(irregular_heart_rhythms).
symptom(vision_changes).
symptom(blurred_vision).
symptom(palpitations).
symptom(asymptomatic).
symptom(high_blood_pressure_reading).
symptom(excessive_thirst).
symptom(frequent_urination).
symptom(excessive_hunger).
symptom(slow_healing_wounds).
symptom(tingling_hands_feet).
symptom(polydipsia).
symptom(polyuria).
symptom(polyphagia).
symptom(neuropathy).
symptom(dark_urine).
symptom(pale_stool).
symptom(right_upper_abdominal_pain).
symptom(loss_of_appetite).
symptom(body_fluids_exposure).
symptom(sudden_high_fever).
symptom(severe_headache).
symptom(neck_stiffness).
symptom(photophobia).
symptom(altered_consciousness).
symptom(rash).
symptom(meningitis_belt_exposure).
symptom(burning_epigastric_pain).
symptom(bloating).
symptom(reflux).
symptom(nighttime_pain).
symptom(nsaid_use).
symptom(burning_epigastric_pain_meal_related).
symptom(epigastric_pain).
symptom(stress_history).
symptom(relief_with_food).
symptom(intermittent_wheeze).
symptom(night_cough).
symptom(early_morning_cough).
symptom(chest_tightness).
symptom(shortness_of_breath).
symptom(dust_trigger).
symptom(cold_air_trigger).
symptom(exercise_trigger).
symptom(wheezing).
symptom(coughing).
symptom(dyspnea).
symptom(exercise_induced).
symptom(high_fever).
symptom(runny_nose).
symptom(red_watery_eyes).
symptom(koplik_spots).
symptom(spreading_rash).
symptom(coryza).
symptom(conjunctivitis).
symptom(maculopapular_rash).
symptom(red_eyes).
symptom(unvaccinated_child).
symptom(unvaccinated).
symptom(dysuria).
symptom(urgency).
symptom(frequency).
symptom(suprapubic_pain).
symptom(cloudy_urine).
symptom(foul_urine).
symptom(flank_pain).
symptom(female).
symptom(sudden_fever).
symptom(muscle_pain).
symptom(back_pain).
symptom(bleeding).
symptom(black_vomit).
symptom(myalgia).
symptom(unvaccinated).
symptom(peripheral_vision_loss).
symptom(tunnel_vision).
symptom(gradual_vision_loss).
symptom(severe_eye_pain).
symptom(red_eyes).
symptom(halos_around_lights).
symptom(eye_pain).
symptom(halos).
symptom(increased_intraocular_pressure).
symptom(optic_nerve_damage).
symptom(chronic_limb_swelling).
symptom(scrotal_swelling).
symptom(recurrent_skin_infections).
symptom(heaviness_of_legs).
symptom(elephantiasis).
symptom(endemic_area_exposure).
symptom(lymphedema).
symptom(severe_itching).
symptom(skin_rash).
symptom(subcutaneous_nodules).
symptom(eye_irritation).
symptom(visual_problems).
symptom(severe_pruritus).
symptom(nodules).
symptom(visual_impairment).
symptom(river_side_exposure).
symptom(skin_changes).
symptom(eye_disease).
symptom(ear_pain).
symptom(irritability).
symptom(reduced_hearing).
symptom(ear_tugging).
symptom(ear_discharge).
symptom(child).
symptom(otalgia).
symptom(hearing_loss).
symptom(otorrhea).
symptom(petechial_rash).
symptom(purpuric_rash).
symptom(crowded_setting).
symptom(meningitis_belt).
symptom(altered_mental_status).
symptom(abdominal_cramps).
symptom(contaminated_food_water_exposure).
symptom(dehydration).
symptom(watery_diarrhea).
symptom(contaminated_food_exposure).
symptom(abnormal_liver_enzymes).
symptom(transfusion_history).
symptom(unsafe_injection_history).